### ISSUE TITLE
Sudo mode password validation errors do not show in SS 3.x or 4.4

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-security-extensions#15]
See https://github.com/silverstripe/silverstripe-security-extensions/pull/14#pullrequestreview-269897056

**Comment by robbieaverill** [comment]
Still an issue

**Comment by robbieaverill** [comment]
The problem is that `#sudoModePassword` (the text input) doesn't get `is-invalid` applied to its class list when it fails validation. This could be a difference in Bootstrap versions, maybe. This should be controlled by Reactstrap based on whether you pass `valid:true|false` as a component prop. We've seen problems with how it handles this versus `invalid` before, so maybe needs to be tinkered with a bit more.

I've tried to replicate this via the Reactstrap starter project they suggest you use to show your bugs when you report them, but wasn't able to with React 16, Bootstrap 4.3.

**Comment by emteknetnz** [comment]
Fixed in:
SS4 https://github.com/silverstripe/silverstripe-security-extensions/pull/34
SS3 https://github.com/silverstripe/silverstripe-security-extensions/pull/35
