### ISSUE TITLE
Sudo mode check relies on "Email" as the name of the unique identifier for users 

### ISSUE THREAD

**Issue by indygriffiths** [silverstripe/silverstripe-security-extensions#18]
In the backported 3.0 branch it's always assumed that `Email` is the field to use for the unique identifier. Came up as we've been implementing the `activedirectory` module which uses `Login` as the form field name, as it's possible for a user to log in using their email or LDAP username.

https://github.com/silverstripe/silverstripe-security-extensions/blob/3.0/src/Control/SudoModeController.php#L129

We're implementing our own version of this controller, however it'd still be an issue for out-of-the-box installations that are using the CMS with an custom authenticator. Not sure the best solution as there's no solid API in SS3 for specifiying the name of the form field for the unique identifier (up to the implementation of `$authenticator::authenticate($authenticationData)` to read the passed in array)

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-security-extensions/pull/19
