### ISSUE TITLE
Help links still redirect to Google

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-security-extensions#28]
PR for 4: https://github.com/silverstripe/silverstripe-security-extensions/pull/29

PR for 3: https://github.com/silverstripe/silverstripe-security-extensions/pull/30

**Comment by robbieaverill** [comment]
Whoops

**Comment by brynwhyman** [comment]
PRs coming

**Comment by dhensby** [comment]
closing as fixed - reopen if I'm wrong

**Comment by brynwhyman** [comment]
Can someone please help tagging new patch releases of `3` and `4` to pull these changes in?

cc @robbieaverill @Cheddam

**Comment by robbieaverill** [comment]
@brynwhyman sure, will do now

**Comment by robbieaverill** [comment]
This doesn't have a 3.0.0 stable yet, so I'll use that for the SS3 version
